[server]
# The port where the server will listen for client and browser connections.
port = 8501

[theme]
primaryColor="#f63366"
backgroundColor="#0e1117"
secondaryBackgroundColor="#31333F"
textColor="#fafafa"
font="sans serif"
